apiVersion: apps/v1
kind: Deployment
metadata:
  name: jungle-book-coll-a74e6ba2c2a749c7a6a167ea3c6fc591-depl
  labels:
    app: jungle-book-coll-a74e6ba2c2a749c7a6a167ea3c6fc591
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jungle-book-coll-a74e6ba2c2a749c7a6a167ea3c6fc591
  template:
    metadata:
      labels:
        app: jungle-book-coll-a74e6ba2c2a749c7a6a167ea3c6fc591
    spec:
      containers:
        - name: jungle-book-coll-a74e6ba2c2a749c7a6a167ea3c6fc591
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:jungle-book-coll-a74e6ba2c2a749c7a6a167ea3c6fc591
          imagePullPolicy: Always
          ports:
            - containerPort: 9016